---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    name: platform
    environment: production

---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring

---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    name: keda
